dist: xenial
language: python
python: 3.7
sudo: false
cache: pip
env:
  - TOXENV=pyparsing1
  - TOXENV=flask08
  - TOXENV=flask09
  - TOXENV=no-flask-cache
  - TOXENV=coverage
  - TOXENV=lint
  - TOXENV=docs

addons:
  apt:
    packages:
      - libcairo2-dev

install:
  - pip install tox

script: "./.travis.sh"

matrix:
  include:
    - python: 3.7
      env:
      - TOXENV=py37
    - python: 3.6
      env:
      - TOXENV=py36
    - python: 3.5
      env:
      - TOXENV=py35
    - python: 3.4
      env:
      - TOXENV=py34
    - python: 2.7
      env:
      - TOXENV=py27
    - python: pypy
      env:
      - TOXENV=pypy
  allow_failures:
    - env: TOXENV=coverage
    - env: TOXENV=pyparsing1
    - env: TOXENV=pypy
